version: '3'

volumes:
  paleo_hurricane_api_local_postgres_data: {}
  paleo_hurricane_api_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: paleo_hurricane_api_local_django
    container_name: paleo_hurricane_api_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/m1.Dockerfile
    image: paleo_hurricane_api_production_postgres
    container_name: paleo_hurricane_api_local_postgres
    volumes:
      - paleo_hurricane_api_local_postgres_data:/var/lib/postgresql/data:Z
      - paleo_hurricane_api_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
