# Generated by Django 4.0.8 on 2022-11-30 16:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geom_line', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('geom_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('publication_title', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('online_resource', models.CharField(blank=True, max_length=100)),
                ('oldest_year', models.IntegerField(blank=True, null=True)),
                ('newest_year', models.IntegerField(blank=True, null=True)),
                ('core_length', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
