# Generated by Django 4.0.8 on 2022-12-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0004_datasite_compilation_datasite_proxy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasite',
            name='compilation',
            field=models.CharField(blank=True, choices=[('Bahamas Compilation', 'Bahamas Compilation'), ('New England Compilation', 'New England Compilation'), ('Florida Gulf of Mexico Compilation', 'Florida Gulf of Mexico Compilation'), ('Mann et al. 2009 Compilation', 'Mann et al. 2009 Compilation'), ('N/A', 'N/A')], max_length=50),
        ),
    ]
