# Generated by Django 4.0.8 on 2022-12-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0007_alter_datapoint_max_age_alter_datapoint_median_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='sand',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_files')),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='data_sites.datasite')),
            ],
        ),
    ]
