# Generated by Django 4.0.8 on 2023-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0008_alter_datapoint_sand_datafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('publication_title', models.CharField(blank=True, max_length=255)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_journal', models.CharField(blank=True, max_length=100)),
                ('publication_volume', models.CharField(blank=True, max_length=100)),
                ('publication_edition', models.CharField(blank=True, max_length=100)),
                ('publication_issue', models.CharField(blank=True, max_length=100)),
                ('publication_pages', models.CharField(blank=True, max_length=100)),
                ('publication_report_number', models.CharField(blank=True, max_length=100)),
                ('publication_doi', models.CharField(blank=True, max_length=100)),
                ('online_resource', models.CharField(blank=True, max_length=100)),
                ('oldest_year', models.IntegerField(blank=True, null=True)),
                ('newest_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
    ]
