# Generated by Django 4.0.8 on 2023-10-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0009_compilation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasite',
            name='compilation',
        ),
    ]
