# Generated by Django 4.0.8 on 2023-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0011_datasite_compilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='compilations/'),
        ),
    ]
