# Generated by Django 4.0.8 on 2023-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0012_compilation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasite',
            name='depth_y_axis_label',
            field=models.CharField(blank=True, default='Sand (mg/cm3)', max_length=100),
        ),
        migrations.AlterField(
            model_name='datasite',
            name='resolution',
            field=models.CharField(blank=True, choices=[('0-3 years', '0-3 years'), ('3-30 years', '3-30 years'), ('>30 years', '>30 years')], default='Sediment', max_length=20),
        ),
    ]
