# Generated by Django 4.0.8 on 2023-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0013_datasite_depth_y_axis_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='intense_event_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
