# Generated by Django 4.0.8 on 2023-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sites', '0014_datapoint_intense_event_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='sand',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
